### ISSUE TITLE
error after press button "save"

### ISSUE THREAD

**Issue by rufusgor** [robertsLando/Mqtt2Mqtt#8]
/opt/Mqtt2Mqtt/node_modules/mqtt/lib/client.js:622
          cb.apply(null, arguments)
             ^

TypeError: cb.apply is not a function
    at /opt/Mqtt2Mqtt/node_modules/mqtt/lib/client.js:622:14
    at Store.close (/opt/Mqtt2Mqtt/node_modules/mqtt/lib/store.js:136:5)
    at /opt/Mqtt2Mqtt/node_modules/mqtt/lib/client.js:620:26
    at Store.close (/opt/Mqtt2Mqtt/node_modules/mqtt/lib/store.js:136:5)
    at Immediate.closeStores (/opt/Mqtt2Mqtt/node_modules/mqtt/lib/client.js:619:24)
    at processImmediate (internal/timers.js:458:21)

**Comment by robertsLando** [comment]
Please try to disable persistent store and let me know

**Comment by robertsLando** [comment]
51328103219f7706def4587ba939b24803e55da3

Try to pull latest commit from master and retry

**Comment by rufusgor** [comment]
I updated it, then disabled the persistent store. the error remained. 
If use a pre-built build for x86, there are no such problems .

/opt/Mqtt2Mqtt/node_modules/mqtt/lib/client.js:622
          cb.apply(null, arguments)
             ^

TypeError: cb.apply is not a function
    at /opt/Mqtt2Mqtt/node_modules/mqtt/lib/client.js:622:14
    at Store.close (/opt/Mqtt2Mqtt/node_modules/mqtt/lib/store.js:136:5)
    at /opt/Mqtt2Mqtt/node_modules/mqtt/lib/client.js:620:26
    at Store.close (/opt/Mqtt2Mqtt/node_modules/mqtt/lib/store.js:136:5)
    at Immediate.closeStores (/opt/Mqtt2Mqtt/node_modules/mqtt/lib/client.js:619:24)
    at processImmediate (internal/timers.js:458:21)

**Comment by robertsLando** [comment]
Please after pull remove node_modules and re-run npm install

**Comment by rufusgor** [comment]
done, but when I add a new map and click save an error appears
